theme: minima
title: Computation of Pump-Leak Flux Balance in Animal Cells
author:
  name: Alexey Vereninov
description: > # this means to ignore newlines until "show_excerpts:"
  Many vital processes in animal cells depend on monovalent ion transport across the plasma membrane via specific pathways.
  Their operation is described by a set of nonlinear and transcendental equations that cannot be solved analytically.
  
header_pages:
 - cellionfluxes.html

